version: "3.5"

services:

  api:
    expose:
      - "8000"
    environment:
      - DATABASE_HOST=pgbouncer
      - REDIS_HOST=redis
    #    image: julioriffel/rinha_backend_django:latest
    build: .
    entrypoint: python -m gunicorn rinha_backend.asgi:application --workers 3 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    depends_on:
      - redis
      - db
    deploy:
      resources:
        limits:
          #          cpus: "0.6"
          memory: "150MB"
      replicas: 2

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          #          cpus: "0.17"
          memory: "25MB"

  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    command: [ "-c", "shared_buffers=128MB", "-c", "synchronous_commit=off", "-c", "fsync=off", "-c", "full_page_writes=off" ]
    deploy:
      resources:
        limits:
          #          cpus: "0.2"
          memory: "175MB"

  pgbouncer:
    image: edoburu/pgbouncer:latest
    env_file:
      - ./.env
    environment:
      DATABASE_URL: "${POSTGRES_DATABASE_URL}"
      authType: scram-sha-256
    ports:
      - "5432:5432"
    depends_on:
      - db
    deploy:
      resources:
        limits:
#          cpus: "0.1"
          memory: "25MB"

  redis:
    image: redis:latest
    hostname: redis
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
#          cpus: "0.1"
          memory: "25MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
