version: "3.5"

services:

  api01: &api
    hostname: api01
    environment:
      - DATABASE_HOST=db
      - REDIS_HOST=redis
    image: julioriffel/rinha_backend_django:latest
    entrypoint: python -m gunicorn rinha_backend.asgi:application --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    ports:
      - "8081:8000"
  #    deploy:
  #      resources:
  #        limits:
  #          cpus: "0.4"
  #          memory: "160MB"

  api02:
    # Essa sintaxe reusa o que foi declarado em 'api01'.
    <<: *api
    hostname: api02
    environment:
      - DATABASE_HOST=db
      - REDIS_HOST=redis
    ports:
      - "8082:8000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      # Obrigatório expor/usar a porta 9999 no load balancer!
      - "9999:9999"
  #    deploy:
  #      resources:
  #        limits:
  #          cpus: "0.1"
  #          memory: "20MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
  #    deploy:
  #      resources:
  #        limits:
  #          cpus: "0.7"
  #          memory: "210MB"
  redis:
    image: redis:7.2.4-alpine3.19
    hostname: redis
    ports:
      - "6379:6379"
#    deploy:
#      resources:
#        limits:
#          cpus: "0.1"
#          memory: 10MB

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
