version: "3.8"

services:

  api:
    expose:
      - "8000"
    environment:
      - DATABASE_HOST=pgbouncer
      - REDIS_HOST=redis
    #    image: julioriffel/rinha_backend_django:latest
    build: .
    entrypoint: python -m gunicorn rinha_backend.asgi:application --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    depends_on:
      - redis
      - db
    deploy:
      resources:
        limits:
          cpus: "0.61"
          memory: "180MB"
      replicas: 2

  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    command: [ "-c", "shared_buffers=128MB", "-c", "synchronous_commit=off", "-c", "fsync=off", "-c", "full_page_writes=off" ]
    deploy:
      resources:
        limits:
          cpus: "0.09"
          memory: "90MB"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.08"
          memory: "65MB"

  pgbouncer:
    image: edoburu/pgbouncer:latest
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/postgres"
      AUTH_TYPE: plain
      ADMIN_USERS: postgres,dbuser
      POOL_MODE: transaction
      MAX_DB_CONNECTIONS: "100"
      MAX_USER_CONNECTIONS: "1000"
      DEFAULT_POOL_SIZE: "40"
      MIN_POOL_SIZE: "40"
      LOG_FILE: /dev/null
    ports:
      - "5432:5432"
    depends_on:
      - db
    volumes:
      - ./pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini:ro
    deploy:
      resources:
        limits:
          cpus: "0.07"
          memory: "10MB"


  redis:
    image: redis:latest
    hostname: redis
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: "0.04"
          memory: "25MB"

networks:
  default:
    driver: bridge
    name: rinha-django
