version: "3.5"

services:

  api01: &api
    hostname: api01
    environment:
      - DATABASE_HOST=db
      - REDIS_HOST=redis
#    image: julioriffel/rinha_backend_django:latest
    build: .
    entrypoint: python -m gunicorn rinha_backend.asgi:application --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    ports:
      - "8081:8000"
    depends_on:
      - redis
      - db
    deploy:
      resources:
        limits:
#          cpus: "1.5"
          memory: "150MB"

  api02:
    <<: *api
    hostname: api02
    ports:
      - "8082:8000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
#          cpus: "0.17"
          memory: "25MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    deploy:
      resources:
        limits:
#          cpus: "0.5"
          memory: "200MB"

  redis:
    image: redis:latest
    hostname: redis
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
#          cpus: "0.05"
          memory: "25MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
